### ISSUE TITLE
what are the Field and Row Terminators?

### ISSUE THREAD

**Issue by mhashim6** [ceefour/hadith-islamware#1]
I want to export the .csv file to a SQL database file, but I don't know the Field and Row Terminators.

**Comment by ceefour** [comment]
Hi, @mhashim6 for any CSV file you found you can usually inspect this visually:

https://raw.githubusercontent.com/ceefour/hadith-islamware/master/hadith-sunan-al-darimi.utf8.csv
![image](https://user-images.githubusercontent.com/24123/27468074-c77ace10-5811-11e7-90b9-9f343a5fe397.png)

So you can see the field terminator is "|" and row terminator is LF (newline).

**Comment by mhashim6** [comment]
the line (row) terminator in this file is \n0| though.
