### ISSUE TITLE
Cara import ke sql gmana ya?

### ISSUE THREAD

**Issue by deka2012** [ceefour/hadith-islamware#2]

**Comment by ceefour** [comment]
Formatnya CSV mas @deka2012 , untuk PostgreSQL dapat menggunakan perintah COPY -> https://stackoverflow.com/questions/2987433/how-to-import-csv-file-data-into-a-postgresql-table

**Comment by deka2012** [comment]
Kalau pakainya xampp? #barupemula

Pada tanggal 4 Okt 2017 12.56 AM, "Hendy Irawan" <notifications@github.com>
menulis:

**Comment by ceefour** [comment]
@deka2012 MySQL/MariaDB juga mendukung CSV koq mas: https://www.google.co.id/search?q=how+to+import+csv+to+mysql

**Comment by deka2012** [comment]
Kan saya pake php myadmin kan mas, trs saya import ke db galat trs.. saya
pake query juga masih gak sukses.. gimana ya mas, saya makin bingung..
mohon bantuananya, baru pertama kali import csv

Pada tanggal 4 Okt 2017 1.16 AM, "Hendy Irawan" <notifications@github.com>
menulis:

**Comment by ceefour** [comment]
Mungkin mas @deka2012 bisa coba konsultasi di forum pengguna MySQL, sehingga bisa mendapatkan jawaban yang lebih memuaskan.  Salah satunya di sini : https://web.facebook.com/groups/mysql.indonesia/

**Comment by deka2012** [comment]
Terimakasih atas info nyaa ..

Pada tanggal 4 Okt 2017 1.27 AM, "Hendy Irawan" <notifications@github.com>
menulis:
