### ISSUE TITLE
Asking about the origin of the source

### ISSUE THREAD

**Issue by gumuruhsspj** [ceefour/hadith-islamware#3]
Assalamu'alaikum warahmatullah,

Ma syaa allah,... such a great enourmous (good) work!

May I ask few question, here....?

I saw the cvs is a very large dataset. But those files were obtained from whom originally? 
since i tried visiting Islamware but found several errors:

> This server could not prove that it is www.islamware.com; its security certificate expired 656 days ago

Is that a copied (translated of) Maktabah Syamilah (arabic) main source?

Wa barakallahu fiikum.
Regards,

**Comment by ceefour** [comment]
This was from islamware.com when it still existed. As you noticed, unfortunately that site is no longer maintained.

Check how it was during its live days:

https://web.archive.org/web/20130603073909/http://islamware.com/
